"""Add password column to users

Revision ID: 7f03d765866d
Revises: 9d49edc85426
Create Date: 2024-09-21 22:19:29.753737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f03d765866d'
down_revision: Union[str, None] = '9d49edc85426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('users')
    # op.drop_table('user_providers')
    # op.drop_table('oauth_providers')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('oauth_providers',
    # sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('oauth_providers_id_seq'::regclass)"), autoincrement=True, nullable=False),
    # sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('provider_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('id', name='oauth_providers_pkey'),
    # sa.UniqueConstraint('provider_name', name='oauth_providers_provider_name_key'),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('user_providers',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], name='user_providers_provider_id_fkey'),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_providers_user_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='user_providers_pkey'),
    # sa.UniqueConstraint('provider_user_id', name='user_providers_provider_user_id_key')
    # )
    # op.create_table('users',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    # sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='users_pkey'),
    # sa.UniqueConstraint('email', name='users_email_key'),
    # sa.UniqueConstraint('name', name='users_name_key')
    # )

    op.drop_column('users', 'password')

    # ### end Alembic commands ###
